name: CI/CD Pipeline

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  lint-backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies for backend
      run: |
        cd backend
        npm install

    - name: Run ESLint for backend
      run: |
        cd backend
        npx eslint .

  build-backend:
    runs-on: ubuntu-latest
    needs: lint-backend

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies for backend
      run: |
        cd backend
        npm install

    - name: Build backend project
      run: |
        cd backend
        npm run dev
