name: CI/CD Pipeline

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  lint-backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install ESLint globally
      run: npm install -g eslint

    - name: Install dependencies for backend
      run: |
        cd backend
        npm install

    - name: Run ESLint for backend
      run: |
        cd backend
        eslint src --ext .ts,.js

  lint-frontend:
    runs-on: ubuntu-latest
    needs: lint-backend

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install ESLint globally
      run: npm install -g eslint

    - name: Install dependencies for frontend
      run: |
        cd frontend
        npm install

    - name: Run ESLint for frontend
      run: |
        cd frontend
        eslint src --ext .ts,.js

  build-backend:
    runs-on: ubuntu-latest
    needs: lint-frontend

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies for backend
      run: |
        cd backend
        npm install

    - name: Build backend project
      run: |
        cd backend
        npm run build  # Assuming you have a build script for the backend

  build-frontend:
    runs-on: ubuntu-latest
    needs: build-backend

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies for frontend
      run: |
        cd frontend
        npm install

    - name: Build frontend project
      run: |
        cd frontend
        npm run build  # Assuming you have a build script for the frontend
